server:
  port: 8088
spring:
  application:
    name: test_poolsize
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qchbs?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone = GMT
    username: root
    password: root
    location: E:\\software\\repository\\mysql\\mysql-connector-java\\8.0.29\\mysql-connector-java-8.0.29.jar


  # 异步线程配置
  # 配置核心线程数
  #  async.executor.thread.core_pool_size = 30
  # 配置最大线程数
  #  async.executor.thread.max_pool_size = 30
  # 配置队列大小
  #  async.executor.thread.queue_capacity = 99988
  # 配置线程池中的线程的名称前缀
#  async.executor.thread.name.prefix = async-importDB-

async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 20
      queue_capacity: 5
      name:
        prefix: async-importDB-