#集成mysql数据库的配置
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/qchbs?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone = GMT
    username: root
    password: root
    location: E:\\software\\repository\\mysql\\mysql-connector-java\\8.0.29\\mysql-connector-java-8.0.29.jar

